//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class aof
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aof()
        {
            this.neisp_pko = new HashSet<neisp_pko>();
        }
    
        public string num_act { get; set; }
        public string stanc { get; set; }
        public Nullable<int> p_close { get; set; }
        public Nullable<System.DateTime> data_sost { get; set; }
        public string num_tr { get; set; }
        public string ind_tr { get; set; }
        public Nullable<System.DateTime> data_prib { get; set; }
        public string way { get; set; }
        public string peregon { get; set; }
        public string st_otp { get; set; }
        public string dr_otp { get; set; }
        public string st_naz { get; set; }
        public string dr_naz { get; set; }
        public string opis_neisp { get; set; }
        public string cod_dl1 { get; set; }
        public string fio1 { get; set; }
        public string cod_dl2 { get; set; }
        public string fio2 { get; set; }
        public string cod_dl3 { get; set; }
        public string fio3 { get; set; }
        public string cod_dl4 { get; set; }
        public string fio4 { get; set; }
        public string cod_dl5 { get; set; }
        public string fio5 { get; set; }
        public string cod_dl6 { get; set; }
        public string fio6 { get; set; }
        public string cod_dl7 { get; set; }
        public string fio7 { get; set; }
        public int act_id { get; set; }
        public Nullable<int> prik_id { get; set; }
        public string otp_dos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<neisp_pko> neisp_pko { get; set; }
    }
}
