//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class aof_cont
    {
        public string in_vgn { get; set; }
        public Nullable<int> act_id { get; set; }
        public string n_cont { get; set; }
        public string n_otpr { get; set; }
        public string cod_garm { get; set; }
    }
}
