//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar_vag
    {
        public Nullable<int> ar_id { get; set; }
        public string in_vgn { get; set; }
        public int av_id { get; set; }
        public string nam { get; set; }
        public string name_ww { get; set; }
        public string stanc { get; set; }
    
        public virtual arenda arenda { get; set; }
    }
}
