//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsp
    {
        public string fam_dsp { get; set; }
        public string fam_oper { get; set; }
        public Nullable<System.DateTime> time_priem { get; set; }
        public Nullable<System.DateTime> time_sdachi { get; set; }
        public string num_DSP { get; set; }
        public string counter { get; set; }
        public string stanc { get; set; }
        public string fam_manevr { get; set; }
        public string fam_dnc { get; set; }
        public string fam_dspg { get; set; }
        public string fam_dspc { get; set; }
    }
}
