//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dsp_info
    {
        public string dop_info { get; set; }
        public string num_dsp { get; set; }
        public System.DateTime data_ins { get; set; }
        public string station { get; set; }
    }
}
