//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dviz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dviz()
        {
            this.gruz_v = new HashSet<gruz_v>();
            this.oper_v = new HashSet<oper_v>();
        }
    
        public Nullable<System.DateTime> prib { get; set; }
        public Nullable<System.DateTime> otpr { get; set; }
        public string esr_s { get; set; }
        public string sost { get; set; }
        public int dviz_id { get; set; }
        public string in_vgn { get; set; }
        public string stanc { get; set; }
        public string kateg { get; set; }
        public Nullable<System.DateTime> prib_pp { get; set; }
        public Nullable<System.DateTime> otpr_pp { get; set; }
        public string ind_s { get; set; }
        public Nullable<int> days { get; set; }
        public string arenda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gruz_v> gruz_v { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oper_v> oper_v { get; set; }
    }
}
