//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWH_oper
    {
        public int id_oper { get; set; }
        public string in_vgn { get; set; }
        public string rod { get; set; }
        public string rod_u { get; set; }
        public string cod_op { get; set; }
        public string cod_ut { get; set; }
        public System.DateTime date_op { get; set; }
        public string station { get; set; }
        public string vid { get; set; }
        public string ves { get; set; }
        public string st_nazn { get; set; }
        public string st_otpr { get; set; }
        public string grpl { get; set; }
        public string cod_otpr { get; set; }
        public string tip_nr { get; set; }
        public string tip_rp { get; set; }
        public string tip_kn { get; set; }
        public string tip_m { get; set; }
        public string cod_garm { get; set; }
        public string st_pogr { get; set; }
        public string cod_gr { get; set; }
        public Nullable<int> gr_snt { get; set; }
        public Nullable<int> por_snt { get; set; }
        public Nullable<int> gr_knt { get; set; }
        public Nullable<int> por_knt { get; set; }
        public string tip_way { get; set; }
        public int id_savs { get; set; }
        public System.DateTime date_work { get; set; }
        public string prFictVigr { get; set; }
        public Nullable<int> ves_kg { get; set; }
    }
}
