//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWH_service
    {
        public int id_service { get; set; }
        public int op_id { get; set; }
        public byte priznak { get; set; }
        public string in_vgn { get; set; }
        public string cod_op { get; set; }
        public string cod_ut { get; set; }
        public Nullable<System.DateTime> date_op { get; set; }
        public string station { get; set; }
    }
}
