//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIR_Info
    {
        public Nullable<int> nameID { get; set; }
        public Nullable<int> smID { get; set; }
        public string longInfo { get; set; }
        public string shortInfo { get; set; }
        public Nullable<System.DateTime> timeBegin { get; set; }
        public Nullable<System.DateTime> timeEnd { get; set; }
        public Nullable<int> sign { get; set; }
        public int id_girInfo { get; set; }
    }
}
