//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gruz_v_ish
    {
        public string nom_v { get; set; }
        public string in_vgn { get; set; }
        public string vid { get; set; }
        public string ves_gr { get; set; }
        public string st_destn { get; set; }
        public string cod_gruz { get; set; }
        public string cod_grpl { get; set; }
        public string mach { get; set; }
        public string cod_prk_gr { get; set; }
        public string negab_vg { get; set; }
        public string plomb { get; set; }
        public string knt_srt { get; set; }
        public string knt_krt { get; set; }
        public string srok_dostav { get; set; }
        public string pogr_st { get; set; }
        public string prim { get; set; }
        public int tr2_id { get; set; }
    }
}
