//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class gy_98
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gy_98()
        {
            this.neisp_pko = new HashSet<neisp_pko>();
        }
    
        public string num_tr { get; set; }
        public string ind_tr { get; set; }
        public Nullable<System.DateTime> data_prib { get; set; }
        public string park { get; set; }
        public string way { get; set; }
        public string neispr { get; set; }
        public string st_pr { get; set; }
        public string lv_pr { get; set; }
        public string prav_pr { get; set; }
        public int ns_id { get; set; }
        public int tr2_id { get; set; }
        public string progn { get; set; }
        public string nomer { get; set; }
        public Nullable<System.DateTime> data_beg_osm { get; set; }
        public Nullable<System.DateTime> data_end_osm { get; set; }
        public int kol { get; set; }
        public string koment { get; set; }
        public string num_gu_106 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<neisp_pko> neisp_pko { get; set; }
    }
}
