//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class har_s
    {
        public string kol_os_s { get; set; }
        public string os_rol { get; set; }
        public string pas_vag { get; set; }
        public string ndlm { get; set; }
        public string kl_knt_stn { get; set; }
        public string kl_knt_ktn { get; set; }
        public int tr_id { get; set; }
    
        public virtual train1 train1 { get; set; }
    }
}
