//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontr_DO2
    {
        public string cod_rps { get; set; }
        public int VO_PR_gr { get; set; }
        public int VO_PR_por { get; set; }
        public int VO_AR_s_pp { get; set; }
        public int VO_PR_s_pp { get; set; }
        public int VO_NOV { get; set; }
        public int VO_PER_25 { get; set; }
        public int VO_IZ_ZK { get; set; }
        public int VO_OTPR_gr { get; set; }
        public int VO_OTPR_por { get; set; }
        public int VO_AR_na_pp { get; set; }
        public int VO_PR_na_pp { get; set; }
        public int VO_ISKL { get; set; }
        public int VO_PER_33 { get; set; }
        public int VO_V_ZK { get; set; }
        public int NAL_P { get; set; }
        public int NAL_RP_gr { get; set; }
        public int NAL_RP_por { get; set; }
        public int NAL_RP_pod_vigr { get; set; }
        public int NAL_RP_pod_sliv { get; set; }
        public int NAL_RP_pod_sort { get; set; }
        public int NAL_NRP { get; set; }
        public int NAL_NRP_zk_tr { get; set; }
        public int NAL_NRP_rez { get; set; }
        public int NAL_NRP_neispr { get; set; }
        public int NAL_NRP_spn { get; set; }
        public int NAL_NRP_ostn { get; set; }
        public int V_ner_gr { get; set; }
        public int V_ner_por { get; set; }
        public int IZ_ner_gr { get; set; }
        public int IZ_ner_por { get; set; }
        public int AR_PR_NA_PP { get; set; }
        public int kol_ch { get; set; }
        public int pr { get; set; }
        public int bl_id { get; set; }
    }
}
