//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontr_kr12
    {
        public Nullable<System.DateTime> date_uh { get; set; }
        public string np { get; set; }
        public string sobstv { get; set; }
        public string no_dog { get; set; }
        public Nullable<System.DateTime> date_dog { get; set; }
        public string num_pr { get; set; }
        public string fio1_st { get; set; }
        public string fio1_kl { get; set; }
        public string fio2_st { get; set; }
        public string fio2_kl { get; set; }
        public string station { get; set; }
        public string cod_kl { get; set; }
        public string tip_dok { get; set; }
        public Nullable<System.DateTime> date_utv { get; set; }
        public int kr_id { get; set; }
        public Nullable<int> prik_id { get; set; }
    }
}
