//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontr_dviz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kontr_dviz()
        {
            this.kontr_oper = new HashSet<kontr_oper>();
        }
    
        public Nullable<System.DateTime> prib { get; set; }
        public Nullable<System.DateTime> otpr { get; set; }
        public string knt_tip { get; set; }
        public string sost { get; set; }
        public int kontr_dviz_id { get; set; }
        public string nom_kont { get; set; }
        public string stanc { get; set; }
        public string kateg { get; set; }
        public Nullable<System.DateTime> prib_pp { get; set; }
        public Nullable<System.DateTime> otpr_pp { get; set; }
        public string ind_s { get; set; }
        public Nullable<int> days { get; set; }
        public string priv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kontr_oper> kontr_oper { get; set; }
    }
}
