//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontr_kr91
    {
        public string num_kr { get; set; }
        public string stanc { get; set; }
        public Nullable<int> p_close { get; set; }
        public Nullable<System.DateTime> data_sost { get; set; }
        public string nom_kont { get; set; }
        public string brutto { get; set; }
        public Nullable<System.DateTime> data_pered { get; set; }
        public string vid_k { get; set; }
        public string tip { get; set; }
        public string neisp_sost { get; set; }
        public string fio_otpr_pol { get; set; }
        public string cod_pol { get; set; }
        public string name_pol { get; set; }
        public string v_z { get; set; }
        public Nullable<System.DateTime> data_v_z { get; set; }
        public string dov_dg { get; set; }
        public string num_dov_dg { get; set; }
        public string fio_vod { get; set; }
        public string num_avto { get; set; }
        public Nullable<System.DateTime> data_ret { get; set; }
        public string cod_dl1 { get; set; }
        public string fio1 { get; set; }
        public string cod_dl2 { get; set; }
        public string fio2 { get; set; }
        public string cod_dl3 { get; set; }
        public string fio3 { get; set; }
        public string cod_dl4 { get; set; }
        public string fio4 { get; set; }
        public int kr91_id { get; set; }
        public Nullable<int> kr_id { get; set; }
        public Nullable<System.DateTime> data_1 { get; set; }
    }
}
