//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontr_gruz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kontr_gruz()
        {
            this.kontr_oper = new HashSet<kontr_oper>();
        }
    
        public string nom_kont { get; set; }
        public string nom_otpk { get; set; }
        public Nullable<System.DateTime> data_otpk { get; set; }
        public string st_otpr { get; set; }
        public string cod_otpr { get; set; }
        public string name_otpr { get; set; }
        public string st_nazn { get; set; }
        public string cod_pol { get; set; }
        public string name_pol { get; set; }
        public string cod_garm_gr { get; set; }
        public string cod_gr { get; set; }
        public string name_gr { get; set; }
        public int ves_gr { get; set; }
        public int massa_gr { get; set; }
        public int kol_mest { get; set; }
        public string rod_upak { get; set; }
        public string tip_razm { get; set; }
        public string ks { get; set; }
        public int massa_tara { get; set; }
        public string mn_st_otpr { get; set; }
        public string prim_kont { get; set; }
        public int kontr_gruz_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kontr_oper> kontr_oper { get; set; }
    }
}
