//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LokM_oper
    {
        public int lokM_work_id { get; set; }
        public string cod_opM { get; set; }
        public string dop_cod { get; set; }
        public Nullable<System.DateTime> dt_beg { get; set; }
        public Nullable<System.DateTime> dt_end { get; set; }
        public string zvk { get; set; }
        public string pw_from { get; set; }
        public string pw_to { get; set; }
        public string prim { get; set; }
        public int lokM_oper_id { get; set; }
        public Nullable<System.DateTime> dt_ins { get; set; }
        public Nullable<int> utv { get; set; }
    
        public virtual LokM_Work LokM_Work { get; set; }
    }
}
