//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class manevry
    {
        public int min_fact { get; set; }
        public Nullable<int> min_okr { get; set; }
        public string place { get; set; }
        public System.DateTime date_vv { get; set; }
        public int op_id { get; set; }
        public int mn_id { get; set; }
        public string prim { get; set; }
    }
}
