//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEISPRAV_VAG
    {
        public string in_vgn { get; set; }
        public int os_id { get; set; }
    
        public virtual OSMOTR OSMOTR { get; set; }
    }
}
