//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class neisp_pko
    {
        public string in_vgn { get; set; }
        public string n_otp { get; set; }
        public Nullable<System.DateTime> data_otp { get; set; }
        public string cod_sbs { get; set; }
        public string cod_gruz { get; set; }
        public string cod_ns { get; set; }
        public Nullable<System.DateTime> data_ob { get; set; }
        public string cod_place { get; set; }
        public string st_otp { get; set; }
        public string st_naz { get; set; }
        public string stanc { get; set; }
        public Nullable<int> ns_id { get; set; }
        public string ves_gruz { get; set; }
        public string otpravit { get; set; }
        public string poluchat { get; set; }
        public Nullable<System.DateTime> dt_otk_akt { get; set; }
        public Nullable<System.DateTime> dt_zak_akt { get; set; }
        public Nullable<int> act_id { get; set; }
        public string n_cont { get; set; }
        public Nullable<System.DateTime> dt_opov_kl { get; set; }
        public string num_tr { get; set; }
        public Nullable<System.DateTime> dt_prib_tr { get; set; }
        public string num_vpu { get; set; }
    
        public virtual aof aof { get; set; }
        public virtual gy_98 gy_98 { get; set; }
    }
}
