//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NNS_act_vag_old
    {
        public string in_vgn { get; set; }
        public string n_pp { get; set; }
        public string remont { get; set; }
        public string ost_prob { get; set; }
        public string prRm { get; set; }
        public string dni { get; set; }
        public string strana { get; set; }
        public string old_gr { get; set; }
        public string new_gr { get; set; }
        public string usl_r { get; set; }
        public Nullable<int> rem_40 { get; set; }
        public string kart { get; set; }
        public string from_prib { get; set; }
        public string op_gost { get; set; }
        public string kat_obr { get; set; }
        public string godn { get; set; }
        public string prim1 { get; set; }
        public string prim2 { get; set; }
        public Nullable<int> nns_act_id { get; set; }
        public Nullable<int> gruz_id { get; set; }
        public string usl_rosp { get; set; }
        public Nullable<int> Vag1 { get; set; }
        public Nullable<int> P_270 { get; set; }
        public string num_svid { get; set; }
        public Nullable<int> dviz_id { get; set; }
        public string data_op { get; set; }
    
        public virtual NNS_act_old NNS_act_old { get; set; }
    }
}
