//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NNS_act_old
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NNS_act_old()
        {
            this.NNS_act_vag_old = new HashSet<NNS_act_vag_old>();
        }
    
        public string num_act { get; set; }
        public string stanc { get; set; }
        public Nullable<int> p_close { get; set; }
        public Nullable<System.DateTime> data_sost { get; set; }
        public string num_tr { get; set; }
        public string ind_tr { get; set; }
        public Nullable<System.DateTime> data_prib { get; set; }
        public string way { get; set; }
        public Nullable<System.DateTime> dt_beg { get; set; }
        public Nullable<System.DateTime> dt_end { get; set; }
        public string cod_dl1 { get; set; }
        public string fio1 { get; set; }
        public string cod_dl2 { get; set; }
        public string fio2 { get; set; }
        public string cod_dl3 { get; set; }
        public string fio3 { get; set; }
        public string cod_dl4 { get; set; }
        public string fio4 { get; set; }
        public string cod_dl5 { get; set; }
        public string fio5 { get; set; }
        public string cod_dl6 { get; set; }
        public string fio6 { get; set; }
        public string cod_dl7 { get; set; }
        public string fio7 { get; set; }
        public string cod_dl8 { get; set; }
        public string fio8 { get; set; }
        public string cod_dl9 { get; set; }
        public string fio9 { get; set; }
        public int nns_act_id { get; set; }
        public string pr_pred { get; set; }
        public string gruz { get; set; }
        public string park { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NNS_act_vag_old> NNS_act_vag_old { get; set; }
    }
}
