//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class oper_v_kps
    {
        public int op_id { get; set; }
        public Nullable<System.DateTime> date_in_kps { get; set; }
        public Nullable<System.DateTime> date_from_kps { get; set; }
        public string status { get; set; }
        public string comments { get; set; }
        public Nullable<int> code { get; set; }
    }
}
