//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class oper_kat_per
    {
        public string kateg { get; set; }
        public int op_id { get; set; }
        public string kateg2 { get; set; }
    
        public virtual oper_v oper_v { get; set; }
    }
}
