//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class oper_way
    {
        public string stanc { get; set; }
        public int oper_way_id { get; set; }
        public string cod_oper { get; set; }
        public Nullable<System.DateTime> date_o { get; set; }
        public Nullable<System.DateTime> date_tr { get; set; }
        public string park { get; set; }
        public string way { get; set; }
        public Nullable<int> long_way { get; set; }
        public string kol_vag { get; set; }
        public string ind_s { get; set; }
        public Nullable<int> oper_tr_id { get; set; }
        public Nullable<int> sm_id { get; set; }
        public Nullable<int> pr { get; set; }
        public Nullable<int> ves_way { get; set; }
        public string in_vgs { get; set; }
        public string in_vgs_put { get; set; }
    
        public virtual SMENA SMENA { get; set; }
    }
}
