//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class oper_tr
    {
        public Nullable<int> ob_train_id { get; set; }
        public string tip_op { get; set; }
        public System.DateTime data_op { get; set; }
        public Nullable<int> tr_id { get; set; }
        public Nullable<int> tr2_id { get; set; }
        public int oper_tr_id { get; set; }
        public string park { get; set; }
        public string way { get; set; }
        public string pole { get; set; }
        public string vc { get; set; }
        public string prim { get; set; }
    
        public virtual ob_train ob_train { get; set; }
        public virtual op_dop_info op_dop_info { get; set; }
    }
}
