//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSMOTR
    {
        public string cod_worker1 { get; set; }
        public string family1 { get; set; }
        public string cod_worker2 { get; set; }
        public string family2 { get; set; }
        public string cod_worker3 { get; set; }
        public string family3 { get; set; }
        public string g_vagon { get; set; }
        public string t_vagon { get; set; }
        public string g_nom { get; set; }
        public string t_nom { get; set; }
        public int tr2_id { get; set; }
        public int os_id { get; set; }
    
        public virtual NEISPRAV_VAG NEISPRAV_VAG { get; set; }
    }
}
