//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PADV_OTPR
    {
        public string in_vgn { get; set; }
        public string cod_oper { get; set; }
        public string nom_otpk { get; set; }
        public Nullable<System.DateTime> data_otpk { get; set; }
        public string nom_pereadr { get; set; }
        public Nullable<System.DateTime> data_pereadr { get; set; }
        public string st_destn { get; set; }
        public string st_otpr { get; set; }
        public string cod_pol { get; set; }
        public string cod_otpr { get; set; }
        public string name_pol { get; set; }
        public string name_otpr { get; set; }
        public Nullable<int> ves_gr { get; set; }
        public Nullable<int> kol_mest { get; set; }
        public string rod_upak { get; set; }
        public string vid_otpk { get; set; }
        public string cod_garm_gr { get; set; }
        public string nom_kont { get; set; }
        public string tip_razm { get; set; }
        public string ks { get; set; }
        public Nullable<int> massa_gr { get; set; }
        public Nullable<int> massa_tara { get; set; }
        public string st_destn_kont { get; set; }
        public string st_otpr_kont { get; set; }
        public string cod_pol_kont { get; set; }
        public string cod_otpr_kont { get; set; }
        public string name_pol_kont { get; set; }
        public string name_otpr_kont { get; set; }
        public string stanc { get; set; }
        public Nullable<System.DateTime> date_tek { get; set; }
        public string arenda { get; set; }
        public int pdv_id { get; set; }
        public string st_pogr { get; set; }
        public string history { get; set; }
    }
}
