//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PADV_VPU_AOF_CKNIS
    {
        public string code { get; set; }
        public string nom_vpu_aof { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string stanc { get; set; }
        public string cod_grpl { get; set; }
        public string disloc { get; set; }
        public int vpa_id { get; set; }
        public string number_full { get; set; }
    }
}
