//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pam_vag
    {
        public string in_vgn { get; set; }
        public int pam_id { get; set; }
        public string numPamPod { get; set; }
        public int ord_num { get; set; }
        public string gr_oper { get; set; }
        public string prin_vag { get; set; }
        public Nullable<System.DateTime> date_pod { get; set; }
        public Nullable<System.DateTime> date_oper { get; set; }
        public Nullable<System.DateTime> date_ubor { get; set; }
        public string zad_gr_oper { get; set; }
        public string num_gu23 { get; set; }
        public string name_gr { get; set; }
        public string cod_admin { get; set; }
        public string name_gr_old { get; set; }
        public string prim_rasch { get; set; }
        public string prim_gr_oper { get; set; }
        public int sader { get; set; }
        public string num_kont { get; set; }
        public string kod_gr_ETSNG { get; set; }
        public string prin_vag_cod { get; set; }
        public string primech { get; set; }
        public Nullable<System.DateTime> date_vigr_sdv { get; set; }
        public string naimen_sobs_dogov { get; set; }
        public string gruzopod { get; set; }
        public Nullable<System.DateTime> date_gu23 { get; set; }
        public string kont_XML { get; set; }
    }
}
