//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pametka
    {
        public int pam_id { get; set; }
        public string stanc { get; set; }
        public string num_pam { get; set; }
        public Nullable<System.DateTime> date_utv { get; set; }
        public short vid_pam { get; set; }
        public string fio_pod { get; set; }
        public string fio_ubor { get; set; }
        public string man_rab { get; set; }
        public string pr_kemProiz { get; set; }
        public string klient_sobs { get; set; }
        public string put_p { get; set; }
        public string k_agent { get; set; }
        public string akt_zader { get; set; }
        public string akt_neoch { get; set; }
        public string akt_povr { get; set; }
        public string akt_iskl { get; set; }
        public string in_vgs { get; set; }
        public Nullable<int> pam_id_asus { get; set; }
        public string e_id { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
        public string pr_doved_ED { get; set; }
        public string lokom { get; set; }
    }
}
