//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class park_now
    {
        public string v1 { get; set; }
        public string v2 { get; set; }
        public string v3 { get; set; }
        public string v4 { get; set; }
        public string v5 { get; set; }
        public string v10 { get; set; }
        public string v11 { get; set; }
        public string v12 { get; set; }
        public string v14 { get; set; }
        public string v16 { get; set; }
        public string v18 { get; set; }
        public int dviz_id { get; set; }
        public int np_id { get; set; }
    
        public virtual nal_park nal_park { get; set; }
    }
}
