//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pass_sostav
    {
        public int ps_id { get; set; }
        public int sostav_id { get; set; }
        public string ind_ps { get; set; }
        public int delta { get; set; }
    }
}
