//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class perev_SAP
    {
        public string stanc { get; set; }
        public string kd_sb { get; set; }
        public string kd_pr { get; set; }
        public string ser_loc { get; set; }
        public string num_loc { get; set; }
        public string fam_m { get; set; }
        public string num_train { get; set; }
        public string ind_s { get; set; }
        public System.DateTime dat_tr { get; set; }
        public int brutto { get; set; }
        public int gr_vsego { get; set; }
        public int por_vsego { get; set; }
        public int kol_vsego { get; set; }
        public int kol_TR1 { get; set; }
        public int kol_TR2 { get; set; }
        public int kol_TP1 { get; set; }
        public int kol_TP2 { get; set; }
        public int kol_TO { get; set; }
        public int kol_TO1 { get; set; }
        public string prim { get; set; }
        public System.DateTime date_ins { get; set; }
        public string komment { get; set; }
        public string num_ch1 { get; set; }
        public string num_ch2 { get; set; }
        public Nullable<int> tr_id { get; set; }
        public int id_per { get; set; }
    }
}
