//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prikaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prikaz()
        {
            this.oper_v = new HashSet<oper_v>();
        }
    
        public string vid_pr { get; set; }
        public string num_pr { get; set; }
        public Nullable<System.DateTime> date_uh { get; set; }
        public string dolg { get; set; }
        public string name { get; set; }
        public string dolg_pr { get; set; }
        public string name_pr { get; set; }
        public Nullable<System.DateTime> dtime_pr { get; set; }
        public string name_os { get; set; }
        public string esrp { get; set; }
        public Nullable<System.DateTime> dtime_rem { get; set; }
        public Nullable<System.DateTime> time_uv { get; set; }
        public string ns1 { get; set; }
        public string ns2 { get; set; }
        public string ns3 { get; set; }
        public string dw { get; set; }
        public int prik_id { get; set; }
        public Nullable<int> vp_id { get; set; }
        public Nullable<int> num_pr_int { get; set; }
        public string rsp1 { get; set; }
        public string rsp2 { get; set; }
        public string rsp3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oper_v> oper_v { get; set; }
    }
}
