//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prikaz_vpu
    {
        public Nullable<System.DateTime> date_uh { get; set; }
        public string np { get; set; }
        public string sobstv { get; set; }
        public string rast_pod { get; set; }
        public string nom_dog { get; set; }
        public Nullable<System.DateTime> date_dog { get; set; }
        public string tip_dok { get; set; }
        public string cod_grpl { get; set; }
        public string num_pr { get; set; }
        public string num_pr_utv { get; set; }
        public string stanc_vpu { get; set; }
        public string mnk { get; set; }
        public string mnk2 { get; set; }
        public string naim { get; set; }
        public string naim2 { get; set; }
        public string stanc { get; set; }
        public int vp_id { get; set; }
        public Nullable<int> num_pr_int { get; set; }
        public Nullable<System.DateTime> date_utv { get; set; }
        public Nullable<int> kol_vag { get; set; }
        public byte pr_vpu { get; set; }
        public string comments { get; set; }
    }
}
