//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prost_vag
    {
        public int dviz_id { get; set; }
        public int pr_v_tr { get; set; }
        public int pr_v_tp { get; set; }
        public int pr_v_mm { get; set; }
        public int pr_v_np { get; set; }
        public int pr_pr_rasf_mm { get; set; }
        public int pr_pr_rasf_tp { get; set; }
        public int pr_rasf_form { get; set; }
        public int pr_rasf_pod_mm { get; set; }
        public int pr_rasf_pod_tp { get; set; }
        public int pr_pod_grop { get; set; }
        public int pr_grop_ub { get; set; }
        public int pr_ub_form_mm { get; set; }
        public int pr_ub_form_tp { get; set; }
        public int pr_form_otpr_mm { get; set; }
        public int pr_form_otpr_tp { get; set; }
        public int pr_pr_pod_mm { get; set; }
        public int pr_pr_pod_tp { get; set; }
        public int pr_ub_otpr_mm { get; set; }
        public int pr_ub_otpr_tp { get; set; }
        public int kol_grop { get; set; }
        public int kol_tp { get; set; }
        public int kol_tr { get; set; }
        public int kol_mm { get; set; }
        public int pr_pd_ub_5_ar { get; set; }
    }
}
