//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prost_vag_for_st
    {
        public int id { get; set; }
        public int dviz_id { get; set; }
        public string station { get; set; }
        public Nullable<long> prost_time { get; set; }
        public Nullable<long> prost_time_np { get; set; }
        public string kateg { get; set; }
        public Nullable<int> kol_gr { get; set; }
    }
}
