//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROST
    {
        public int bl_id { get; set; }
        public decimal kol_ms { get; set; }
        public decimal kol_gr_op { get; set; }
        public int ms { get; set; }
        public decimal prost_sr_ms { get; set; }
        public decimal prost_go_ms { get; set; }
        public decimal kol_tr { get; set; }
        public int tr { get; set; }
        public decimal prost_sr_tr { get; set; }
        public decimal kol_tp { get; set; }
        public int tp { get; set; }
        public decimal prost_sr_tp { get; set; }
        public decimal kol_tt { get; set; }
        public int tt { get; set; }
        public decimal prost_sr_tt { get; set; }
        public decimal kol_gr_op_rf { get; set; }
        public int ms_rf { get; set; }
        public decimal prost_go_rf { get; set; }
        public decimal kol_gr_op_cs { get; set; }
        public int ms_cs { get; set; }
        public decimal prost_go_cs { get; set; }
        public decimal kol_tp_cs { get; set; }
        public int tp_cs { get; set; }
        public decimal prost_sr_cs { get; set; }
        public decimal kol_ms_ch { get; set; }
        public decimal kol_gr_op_ch { get; set; }
        public int ms_ch { get; set; }
        public decimal prost_sr_ms_ch { get; set; }
        public decimal prost_go_ms_ch { get; set; }
        public decimal kol_tr_ch { get; set; }
        public int tr_ch { get; set; }
        public decimal prost_sr_tr_ch { get; set; }
        public decimal kol_tp_ch { get; set; }
        public int tp_ch { get; set; }
        public decimal prost_sr_tp_ch { get; set; }
        public decimal kol_tt_ch { get; set; }
        public int tt_ch { get; set; }
        public decimal prost_sr_tt_ch { get; set; }
        public decimal kol_gr_op_rf_ch { get; set; }
        public int ms_rf_ch { get; set; }
        public decimal prost_go_rf_ch { get; set; }
        public decimal kol_gr_op_cs_ch { get; set; }
        public int ms_cs_ch { get; set; }
        public decimal prost_go_cs_ch { get; set; }
        public decimal kol_tp_cs_ch { get; set; }
        public int tp_cs_ch { get; set; }
        public decimal prost_sr_cs_ch { get; set; }
        public decimal kol_ms_svoi { get; set; }
        public decimal kol_gr_op_svoi { get; set; }
        public int ms_svoi { get; set; }
        public decimal prost_sr_ms_svoi { get; set; }
        public decimal prost_go_ms_svoi { get; set; }
        public decimal kol_tr_svoi { get; set; }
        public int tr_svoi { get; set; }
        public decimal prost_sr_tr_svoi { get; set; }
        public decimal kol_tp_svoi { get; set; }
        public int tp_svoi { get; set; }
        public decimal prost_sr_tp_svoi { get; set; }
        public decimal kol_tt_svoi { get; set; }
        public int tt_svoi { get; set; }
        public decimal prost_sr_tt_svoi { get; set; }
        public decimal kol_gr_op_rf_svoi { get; set; }
        public int ms_rf_svoi { get; set; }
        public decimal prost_go_rf_svoi { get; set; }
        public decimal kol_gr_op_cs_svoi { get; set; }
        public int ms_cs_svoi { get; set; }
        public decimal prost_go_cs_svoi { get; set; }
        public decimal kol_tp_cs_svoi { get; set; }
        public int tp_cs_svoi { get; set; }
        public decimal prost_sr_cs_svoi { get; set; }
        public decimal kol_ms_privat { get; set; }
        public decimal kol_gr_op_privat { get; set; }
        public int ms_privat { get; set; }
        public decimal prost_sr_ms_privat { get; set; }
        public decimal prost_go_ms_privat { get; set; }
        public decimal kol_tr_privat { get; set; }
        public int tr_privat { get; set; }
        public decimal prost_sr_tr_privat { get; set; }
        public decimal kol_tp_privat { get; set; }
        public int tp_privat { get; set; }
        public decimal prost_sr_tp_privat { get; set; }
        public decimal kol_tt_privat { get; set; }
        public int tt_privat { get; set; }
        public decimal prost_sr_tt_privat { get; set; }
        public decimal kol_gr_op_rf_privat { get; set; }
        public int ms_rf_privat { get; set; }
        public decimal prost_go_rf_privat { get; set; }
        public decimal kol_gr_op_cs_privat { get; set; }
        public int ms_cs_privat { get; set; }
        public decimal prost_go_cs_privat { get; set; }
        public decimal kol_tp_cs_privat { get; set; }
        public int tp_cs_privat { get; set; }
        public decimal prost_sr_cs_privat { get; set; }
        public decimal kol_tr_cs { get; set; }
        public int tr_cs { get; set; }
        public decimal prost_tr_sr_cs { get; set; }
        public decimal kol_tr_cs_ch { get; set; }
        public int tr_cs_ch { get; set; }
        public decimal prost_tr_sr_cs_ch { get; set; }
        public decimal kol_tr_cs_svoi { get; set; }
        public int tr_cs_svoi { get; set; }
        public decimal prost_tr_sr_cs_svoi { get; set; }
        public decimal kol_tr_cs_privat { get; set; }
        public int tr_cs_privat { get; set; }
        public decimal prost_tr_sr_cs_privat { get; set; }
    
        public virtual bal_zurn bal_zurn { get; set; }
    }
}
