//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prost_for_st
    {
        public int id { get; set; }
        public int bl_id { get; set; }
        public string station { get; set; }
        public Nullable<int> kol_mm { get; set; }
        public Nullable<decimal> prost_mm { get; set; }
        public Nullable<int> kol_gr { get; set; }
        public Nullable<int> kol_tp { get; set; }
        public Nullable<decimal> prost_tp { get; set; }
    }
}
