//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTO_SAP
    {
        public int REC_ID { get; set; }
        public int Pto_Sap_id { get; set; }
        public string typeOper { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> dateOper { get; set; }
        public string in_vgn { get; set; }
        public Nullable<int> dviz_id { get; set; }
        public string stanc { get; set; }
        public string KS { get; set; }
        public string Priznak { get; set; }
        public string num_tr { get; set; }
        public Nullable<System.DateTime> datePr { get; set; }
        public string vid_rem { get; set; }
        public string cod_neispr1 { get; set; }
        public string cod_neispr2 { get; set; }
        public string cod_neispr3 { get; set; }
        public string cod_neispr4 { get; set; }
        public string cod_neispr5 { get; set; }
        public string num_uvd_23 { get; set; }
        public string cod_PTO { get; set; }
        public Nullable<System.DateTime> data_VU_23 { get; set; }
        public string num_uvd_36 { get; set; }
        public Nullable<System.DateTime> data_VU_36 { get; set; }
        public string cod_Sbs { get; set; }
        public string cod_Ar { get; set; }
        public Nullable<System.DateTime> integration_time { get; set; }
        public Nullable<System.DateTime> receprion_time { get; set; }
        public string vid_rp { get; set; }
        public string place_rp { get; set; }
        public Nullable<System.DateTime> data_rp { get; set; }
        public Nullable<System.DateTime> data_postr { get; set; }
        public string mnk2 { get; set; }
    }
}
