//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_dviz
    {
        public int id_PVdviz { get; set; }
        public string in_vgn { get; set; }
        public string stancTo { get; set; }
        public Nullable<System.DateTime> date_pr { get; set; }
        public Nullable<System.DateTime> date4770_to { get; set; }
        public Nullable<System.DateTime> date_Priem { get; set; }
        public string prPriem { get; set; }
        public string prDoPrm { get; set; }
        public string styk_to { get; set; }
        public string prim_to { get; set; }
        public string nom_ppv_to { get; set; }
        public string pr_sob_to { get; set; }
        public string arenda_to { get; set; }
        public string ind_s_to { get; set; }
        public string stancFrom { get; set; }
        public Nullable<System.DateTime> date_otpr { get; set; }
        public Nullable<System.DateTime> date4770_from { get; set; }
        public Nullable<System.DateTime> date_sdaca { get; set; }
        public string prSdacha { get; set; }
        public string prDoSd { get; set; }
        public string styk_from { get; set; }
        public string prim_from { get; set; }
        public string nom_ppv_from { get; set; }
        public string pr_sob_from { get; set; }
        public string arenda_from { get; set; }
        public string ind_s_from { get; set; }
        public Nullable<int> codErr { get; set; }
    }
}
