//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_dvizSAP
    {
        public int id_PVdvizSAP { get; set; }
        public int id_PVdviz { get; set; }
        public string in_vgn { get; set; }
        public string indS { get; set; }
        public string ks { get; set; }
        public string sob_ot { get; set; }
        public string ar_ot { get; set; }
        public Nullable<System.DateTime> date_ot { get; set; }
        public string stanc_ot { get; set; }
        public string sob_do { get; set; }
        public string ar_do { get; set; }
        public Nullable<System.DateTime> date_do { get; set; }
        public string stanc_do { get; set; }
        public string cod_per { get; set; }
        public string cod_op { get; set; }
        public string nom_ppv_ot { get; set; }
        public string nom_ppv_do { get; set; }
    }
}
