//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class razl_kat_per
    {
        public string cod_kat { get; set; }
        public Nullable<int> rps_g { get; set; }
        public Nullable<int> rps_p { get; set; }
        public Nullable<int> nrp_g { get; set; }
        public Nullable<int> nrp_p { get; set; }
        public int tr_id { get; set; }
        public byte tip_ucheta { get; set; }
    }
}
