//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZ_ZAP
    {
        public string vid_pr { get; set; }
        public string disloc { get; set; }
        public System.DateTime date_o { get; set; }
        public string stanc { get; set; }
        public string in_vgn { get; set; }
        public int prizn { get; set; }
        public string num_pr { get; set; }
    }
}
