//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int id_shift { get; set; }
        public int num_shift { get; set; }
        public System.DateTime date_beg { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public int id_type { get; set; }
    }
}
