//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat_info
    {
        public int si_id { get; set; }
        public int si_type_info { get; set; }
        public Nullable<int> si_count_vans { get; set; }
        public string si_text_data { get; set; }
        public Nullable<int> si_numeric_data { get; set; }
        public Nullable<System.DateTime> si_begin_date { get; set; }
        public Nullable<System.DateTime> si_end_date { get; set; }
        public string si_time_feed_removal { get; set; }
    }
}
