//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr2Pr_ish
    {
        public int tr2Pr_ish_id { get; set; }
        public int tr2_id { get; set; }
        public string login { get; set; }
        public string prich { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
