//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vagon
    {
        public string in_vgn { get; set; }
        public string pr_kach { get; set; }
        public string cod_sobst { get; set; }
        public string roliki { get; set; }
        public string tara_v { get; set; }
        public string col_os_v { get; set; }
        public string rod { get; set; }
        public string kalibr { get; set; }
        public string usl_dl { get; set; }
        public string grpd { get; set; }
        public string privat { get; set; }
        public string Tip_kr { get; set; }
        public Nullable<int> Ispr_PP { get; set; }
        public Nullable<int> Zatv_3 { get; set; }
        public Nullable<int> Par { get; set; }
        public Nullable<int> M_tab { get; set; }
    }
}
