//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vpu_spravka
    {
        public int spr_id { get; set; }
        public int op_id { get; set; }
        public System.DateTime date_tele { get; set; }
        public System.DateTime date_naves { get; set; }
        public System.DateTime date_perev { get; set; }
        public string disl { get; set; }
        public System.DateTime date_navyst { get; set; }
        public int razn { get; set; }
    }
}
