//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VZ_S_VAG_KONT
    {
        public string in_vgn { get; set; }
        public string cod_oper { get; set; }
        public System.DateTime data_oper { get; set; }
        public int ves_gr { get; set; }
        public string st_destn { get; set; }
        public string cod_gruz { get; set; }
        public string cod_pol { get; set; }
        public string march { get; set; }
        public string cod_prk { get; set; }
        public string negab_vgn { get; set; }
        public string plomb { get; set; }
        public string knt_stn { get; set; }
        public string knt_ktn { get; set; }
        public string srok { get; set; }
        public string pogr_st { get; set; }
        public string tara { get; set; }
        public string prim { get; set; }
        public int vk_id { get; set; }
        public string stanc { get; set; }
        public System.DateTime date_tek { get; set; }
    }
}
