//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class way_vag
    {
        public string name_w { get; set; }
        public string inv_vg { get; set; }
        public int w_vg { get; set; }
        public string stanc { get; set; }
    
        public virtual way_a way_a { get; set; }
    }
}
