//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAJ_VAGON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZAJ_VAGON()
        {
            this.ZAJ_OTRAB = new HashSet<ZAJ_OTRAB>();
        }
    
        public string in_vgn { get; set; }
        public string place_pod { get; set; }
        public int z_id { get; set; }
        public Nullable<System.DateTime> date_pod { get; set; }
        public string kolvo { get; set; }
        public Nullable<int> schet { get; set; }
        public string rod { get; set; }
        public string gruz { get; set; }
        public string klient { get; set; }
        public string np_ut { get; set; }
        public Nullable<int> prik_id { get; set; }
        public int zv_id { get; set; }
        public string comments { get; set; }
        public string way_comments { get; set; }
        public string plan_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAJ_OTRAB> ZAJ_OTRAB { get; set; }
        public virtual ZAJAVKA ZAJAVKA { get; set; }
    }
}
