//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class zajavka_por
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zajavka_por()
        {
            this.zajavka_por_vag = new HashSet<zajavka_por_vag>();
        }
    
        public string station { get; set; }
        public string num_z { get; set; }
        public System.DateTime date_z { get; set; }
        public Nullable<System.DateTime> date_pod { get; set; }
        public string cod_grpl { get; set; }
        public short status { get; set; }
        public string stanc_for { get; set; }
        public int kol_vag { get; set; }
        public string rod { get; set; }
        public string ks { get; set; }
        public string st_destn { get; set; }
        public string cod_garm_gr { get; set; }
        public string prim { get; set; }
        public byte pr_vvod { get; set; }
        public int id_z { get; set; }
        public string rw_dest { get; set; }
        public string code_godn_gr { get; set; }
        public string park_way { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zajavka_por_vag> zajavka_por_vag { get; set; }
    }
}
