//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class zajavka_por_vag
    {
        public int id_z { get; set; }
        public string in_vgn { get; set; }
        public System.DateTime date_check { get; set; }
        public string fio { get; set; }
        public string prim { get; set; }
        public short status { get; set; }
        public string route { get; set; }
        public Nullable<int> dviz_id { get; set; }
        public int id_z_v { get; set; }
        public short otpr { get; set; }
    
        public virtual zajavka_por zajavka_por { get; set; }
    }
}
