//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.locoDispatcher.ArchiveDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAJAVKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZAJAVKA()
        {
            this.ZAJ_VAGON = new HashSet<ZAJ_VAGON>();
        }
    
        public string tip { get; set; }
        public Nullable<System.DateTime> date_vv_zaj { get; set; }
        public string cod_grpl { get; set; }
        public string place { get; set; }
        public Nullable<System.DateTime> date_beg { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string nom_dok { get; set; }
        public string dokument { get; set; }
        public string prich { get; set; }
        public string stanc { get; set; }
        public int z_id { get; set; }
        public string cod_adres { get; set; }
        public string num_train { get; set; }
        public Nullable<System.DateTime> date_pr { get; set; }
        public string cod_per { get; set; }
        public string fio_per { get; set; }
        public string cod_pr { get; set; }
        public string fio_pr { get; set; }
        public string stanc_z { get; set; }
        public string cod_adresat { get; set; }
        public string fio_adresat { get; set; }
        public Nullable<int> z_id9_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAJ_VAGON> ZAJ_VAGON { get; set; }
    }
}
