//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM
    {
        public int ADM_ID { get; set; }
        public string KOD { get; set; }
        public short KOD_ISO { get; set; }
        public string Name { get; set; }
        public string SName_R { get; set; }
        public string SName_L { get; set; }
    }
}
