//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARENDA_KLIENTI
    {
        public int KL_ID { get; set; }
        public string Arenda_Kod { get; set; }
        public string Arenda_Nos { get; set; }
        public string Arenda_Nos_L { get; set; }
        public string KAM { get; set; }
    }
}
