//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_NAPR
    {
        public string np { get; set; }
        public string np202_pr { get; set; }
        public string np202_ot { get; set; }
        public string np202 { get; set; }
        public string mins_pr { get; set; }
        public string mins_ot { get; set; }
        public string station { get; set; }
        public string pr_opv { get; set; }
    }
}
