//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECP
    {
        public string station { get; set; }
        public string srv { get; set; }
        public string sid { get; set; }
        public string service_url { get; set; }
        public string tip { get; set; }
    }
}
