//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIO
    {
        public int cod { get; set; }
        public string fio1 { get; set; }
        public string fio_l { get; set; }
        public string tip_arm { get; set; }
        public string station { get; set; }
        public string tek { get; set; }
        public string Dolj { get; set; }
    }
}
