//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIO_Smena
    {
        public int id_fio { get; set; }
        public string activ { get; set; }
        public string dolj { get; set; }
        public string naimR { get; set; }
        public string naimL { get; set; }
        public string fio { get; set; }
        public string nomer { get; set; }
        public Nullable<System.DateTime> data_sst { get; set; }
        public string stanc { get; set; }
    }
}
