//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nsiEntities : DbContext
    {
        public nsiEntities()
            : base("name=nsiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bankrupt> bankrupt { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<GRUZ> GRUZ { get; set; }
        public virtual DbSet<LokM_BasicPr> LokM_BasicPr { get; set; }
        public virtual DbSet<LokM_Stanc> LokM_Stanc { get; set; }
        public virtual DbSet<NPLF2> NPLF2 { get; set; }
        public virtual DbSet<pattern5676> pattern5676 { get; set; }
        public virtual DbSet<perev_ar> perev_ar { get; set; }
        public virtual DbSet<perevoz> perevoz { get; set; }
        public virtual DbSet<pw_uchastok> pw_uchastok { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<Region_stanc> Region_stanc { get; set; }
        public virtual DbSet<rem_Klient> rem_Klient { get; set; }
        public virtual DbSet<rem_Kod_Pred> rem_Kod_Pred { get; set; }
        public virtual DbSet<rem_neisprav> rem_neisprav { get; set; }
        public virtual DbSet<rem_neisprav_pricelist> rem_neisprav_pricelist { get; set; }
        public virtual DbSet<rem_PriceList> rem_PriceList { get; set; }
        public virtual DbSet<RZPor> RZPor { get; set; }
        public virtual DbSet<sad_spis> sad_spis { get; set; }
        public virtual DbSet<SADER> SADER { get; set; }
        public virtual DbSet<shift_type> shift_type { get; set; }
        public virtual DbSet<shortSort> shortSort { get; set; }
        public virtual DbSet<SYS_cfg> SYS_cfg { get; set; }
        public virtual DbSet<SYS_station> SYS_station { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tag5676> tag5676 { get; set; }
        public virtual DbSet<uchastok> uchastok { get; set; }
        public virtual DbSet<uslugi> uslugi { get; set; }
        public virtual DbSet<a1> a1 { get; set; }
        public virtual DbSet<ADM> ADM { get; set; }
        public virtual DbSet<ARENDA_KLIENTI> ARENDA_KLIENTI { get; set; }
        public virtual DbSet<arhiv_clean> arhiv_clean { get; set; }
        public virtual DbSet<bros_pr> bros_pr { get; set; }
        public virtual DbSet<bros_pr_24_25> bros_pr_24_25 { get; set; }
        public virtual DbSet<cargo_vags> cargo_vags { get; set; }
        public virtual DbSet<COD_DOLZ> COD_DOLZ { get; set; }
        public virtual DbSet<CODGRPOR> CODGRPOR { get; set; }
        public virtual DbSet<DOR> DOR { get; set; }
        public virtual DbSet<DSCM> DSCM { get; set; }
        public virtual DbSet<dscm_tmp2> dscm_tmp2 { get; set; }
        public virtual DbSet<DSCM1> DSCM1 { get; set; }
        public virtual DbSet<DSCM_25> DSCM_25 { get; set; }
        public virtual DbSet<DSP_NAPR> DSP_NAPR { get; set; }
        public virtual DbSet<DSP_PRIM> DSP_PRIM { get; set; }
        public virtual DbSet<DSP_PRK> DSP_PRK { get; set; }
        public virtual DbSet<ECP> ECP { get; set; }
        public virtual DbSet<FIO> FIO { get; set; }
        public virtual DbSet<FIO_Smena> FIO_Smena { get; set; }
        public virtual DbSet<gir_pass_tr> gir_pass_tr { get; set; }
        public virtual DbSet<gruz_tmp2> gruz_tmp2 { get; set; }
        public virtual DbSet<HOD> HOD { get; set; }
        public virtual DbSet<IP_ADDR> IP_ADDR { get; set; }
        public virtual DbSet<kl_594514> kl_594514 { get; set; }
        public virtual DbSet<klient> klient { get; set; }
        public virtual DbSet<klient_tmp> klient_tmp { get; set; }
        public virtual DbSet<klient21> klient21 { get; set; }
        public virtual DbSet<klient24> klient24 { get; set; }
        public virtual DbSet<klient_new> klient_new { get; set; }
        public virtual DbSet<KOD_PRED> KOD_PRED { get; set; }
        public virtual DbSet<kontr_ks> kontr_ks { get; set; }
        public virtual DbSet<LoginAdmin> LoginAdmin { get; set; }
        public virtual DbSet<LoginConversion> LoginConversion { get; set; }
        public virtual DbSet<LOKM> LOKM { get; set; }
        public virtual DbSet<LokM_BasicPr_Add> LokM_BasicPr_Add { get; set; }
        public virtual DbSet<LokM_Stanc_Ar> LokM_Stanc_Ar { get; set; }
        public virtual DbSet<M_NEISPRAV> M_NEISPRAV { get; set; }
        public virtual DbSet<M_NEISPRAV_LITLAT> M_NEISPRAV_LITLAT { get; set; }
        public virtual DbSet<m_neisprav_tmp2> m_neisprav_tmp2 { get; set; }
        public virtual DbSet<M_STATE> M_STATE { get; set; }
        public virtual DbSet<M_STATE_LOGs> M_STATE_LOGs { get; set; }
        public virtual DbSet<M101> M101 { get; set; }
        public virtual DbSet<M102> M102 { get; set; }
        public virtual DbSet<M104> M104 { get; set; }
        public virtual DbSet<m104_tmp2> m104_tmp2 { get; set; }
        public virtual DbSet<M107> M107 { get; set; }
        public virtual DbSet<M109> M109 { get; set; }
        public virtual DbSet<M122> M122 { get; set; }
        public virtual DbSet<m122_tmp2> m122_tmp2 { get; set; }
        public virtual DbSet<M124> M124 { get; set; }
        public virtual DbSet<M124_10> M124_10 { get; set; }
        public virtual DbSet<M127> M127 { get; set; }
        public virtual DbSet<M134> M134 { get; set; }
        public virtual DbSet<M135> M135 { get; set; }
        public virtual DbSet<M142> M142 { get; set; }
        public virtual DbSet<m1521> m1521 { get; set; }
        public virtual DbSet<m1522> m1522 { get; set; }
        public virtual DbSet<m1523> m1523 { get; set; }
        public virtual DbSet<m1524> m1524 { get; set; }
        public virtual DbSet<m1673> m1673 { get; set; }
        public virtual DbSet<m170> m170 { get; set; }
        public virtual DbSet<M170___> M170___ { get; set; }
        public virtual DbSet<M172_BEL> M172_BEL { get; set; }
        public virtual DbSet<M172_21> M172_21 { get; set; }
        public virtual DbSet<m5640> m5640 { get; set; }
        public virtual DbSet<mas_index> mas_index { get; set; }
        public virtual DbSet<mkao> mkao { get; set; }
        public virtual DbSet<mppi_stanc24> mppi_stanc24 { get; set; }
        public virtual DbSet<ms1359_1388> ms1359_1388 { get; set; }
        public virtual DbSet<NAPR> NAPR { get; set; }
        public virtual DbSet<NNS_strana> NNS_strana { get; set; }
        public virtual DbSet<NNS_USER> NNS_USER { get; set; }
        public virtual DbSet<NORM> NORM { get; set; }
        public virtual DbSet<NPLF> NPLF { get; set; }
        public virtual DbSet<NPLF2_24> NPLF2_24 { get; set; }
        public virtual DbSet<NPLF2_KLIENT> NPLF2_KLIENT { get; set; }
        public virtual DbSet<NPLF2_KLIENT_24> NPLF2_KLIENT_24 { get; set; }
        public virtual DbSet<NPLF2_LONG_W> NPLF2_LONG_W { get; set; }
        public virtual DbSet<NS_KN> NS_KN { get; set; }
        public virtual DbSet<NS_MESTO> NS_MESTO { get; set; }
        public virtual DbSet<NS_OBST> NS_OBST { get; set; }
        public virtual DbSet<NS_OBST1> NS_OBST1 { get; set; }
        public virtual DbSet<NS_ZPU> NS_ZPU { get; set; }
        public virtual DbSet<nsi_stan> nsi_stan { get; set; }
        public virtual DbSet<nsi_stanrem> nsi_stanrem { get; set; }
        public virtual DbSet<NSSTOT> NSSTOT { get; set; }
        public virtual DbSet<NSSTOT_5> NSSTOT_5 { get; set; }
        public virtual DbSet<nsstot_6_tmp2> nsstot_6_tmp2 { get; set; }
        public virtual DbSet<NUM_POR> NUM_POR { get; set; }
        public virtual DbSet<OPER> OPER { get; set; }
        public virtual DbSet<owner> owner { get; set; }
        public virtual DbSet<owner_tmp2> owner_tmp2 { get; set; }
        public virtual DbSet<park_way_VC> park_way_VC { get; set; }
        public virtual DbSet<PASS_TMP> PASS_TMP { get; set; }
        public virtual DbSet<PASS_TR> PASS_TR { get; set; }
        public virtual DbSet<pattern5676_tag5676> pattern5676_tag5676 { get; set; }
        public virtual DbSet<PEREADR> PEREADR { get; set; }
        public virtual DbSet<perev_lok> perev_lok { get; set; }
        public virtual DbSet<podhodIVC> podhodIVC { get; set; }
        public virtual DbSet<PRKACHV> PRKACHV { get; set; }
        public virtual DbSet<ps> ps { get; set; }
        public virtual DbSet<REGUL> REGUL { get; set; }
        public virtual DbSet<REGUL_25> REGUL_25 { get; set; }
        public virtual DbSet<ROD> ROD { get; set; }
        public virtual DbSet<RP_RS> RP_RS { get; set; }
        public virtual DbSet<RPS> RPS { get; set; }
        public virtual DbSet<RV_Posl> RV_Posl { get; set; }
        public virtual DbSet<ShablonOPKIS> ShablonOPKIS { get; set; }
        public virtual DbSet<shift_employee> shift_employee { get; set; }
        public virtual DbSet<shift_jobtitle> shift_jobtitle { get; set; }
        public virtual DbSet<shortGruz> shortGruz { get; set; }
        public virtual DbSet<shortGruz1> shortGruz1 { get; set; }
        public virtual DbSet<shortSort1> shortSort1 { get; set; }
        public virtual DbSet<SOBSTVENNIK> SOBSTVENNIK { get; set; }
        public virtual DbSet<SootvPrk> SootvPrk { get; set; }
        public virtual DbSet<SootvPrk24> SootvPrk24 { get; set; }
        public virtual DbSet<Spec_nad> Spec_nad { get; set; }
        public virtual DbSet<Spec_nad_s> Spec_nad_s { get; set; }
        public virtual DbSet<specvag24> specvag24 { get; set; }
        public virtual DbSet<SPER1> SPER1 { get; set; }
        public virtual DbSet<STAN> STAN { get; set; }
        public virtual DbSet<STANC> STANC { get; set; }
        public virtual DbSet<STANC_OBRAB> STANC_OBRAB { get; set; }
        public virtual DbSet<stanc_prip> stanc_prip { get; set; }
        public virtual DbSet<STANC_SOBSTV> STANC_SOBSTV { get; set; }
        public virtual DbSet<stanc_uch> stanc_uch { get; set; }
        public virtual DbSet<STFORM> STFORM { get; set; }
        public virtual DbSet<STRANA> STRANA { get; set; }
        public virtual DbSet<SYS_PK> SYS_PK { get; set; }
        public virtual DbSet<TABL_KRT> TABL_KRT { get; set; }
        public virtual DbSet<Time_Klient> Time_Klient { get; set; }
        public virtual DbSet<TXT_ERR> TXT_ERR { get; set; }
        public virtual DbSet<USL1> USL1 { get; set; }
        public virtual DbSet<USL1_21> USL1_21 { get; set; }
        public virtual DbSet<USL2> USL2 { get; set; }
        public virtual DbSet<USL2_21> USL2_21 { get; set; }
        public virtual DbSet<USL3> USL3 { get; set; }
        public virtual DbSet<USL3_21> USL3_21 { get; set; }
        public virtual DbSet<USL4> USL4 { get; set; }
        public virtual DbSet<USL4_21> USL4_21 { get; set; }
        public virtual DbSet<USL5> USL5 { get; set; }
        public virtual DbSet<USL5_25> USL5_25 { get; set; }
        public virtual DbSet<uslug_form> uslug_form { get; set; }
        public virtual DbSet<V_GR_ZAP_POGR> V_GR_ZAP_POGR { get; set; }
        public virtual DbSet<vag_LDZ> vag_LDZ { get; set; }
        public virtual DbSet<VID_OBSL> VID_OBSL { get; set; }
        public virtual DbSet<VOHR> VOHR { get; set; }
    }
}
