//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient_new
    {
        public string cod_kl { get; set; }
        public string mn_kl { get; set; }
        public string mn_kl_str { get; set; }
        public string kodas { get; set; }
    }
}
