//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOD_PRED
    {
        public int PRED_ID { get; set; }
        public int KOD { get; set; }
        public string Name { get; set; }
        public string Sname { get; set; }
        public Nullable<int> DOR_ID { get; set; }
        public Nullable<int> STAN_ID { get; set; }
    }
}
