//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LokM_BasicPr
    {
        public int lokM_basicpr_id { get; set; }
        public string cod_W { get; set; }
        public string basic_pr { get; set; }
        public string basic_pr1 { get; set; }
        public string cod_TPV { get; set; }
        public Nullable<int> nCol_spr { get; set; }
        public Nullable<byte> hand_input { get; set; }
        public System.DateTime dt_from { get; set; }
        public System.DateTime dt_to { get; set; }
    
        public virtual LokM_BasicPr_Add LokM_BasicPr_Add { get; set; }
    }
}
