//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LokM_BasicPr_Add
    {
        public int lokM_basicpr_id { get; set; }
        public string cod_D { get; set; }
        public string Add_pr { get; set; }
        public string Add_pr1 { get; set; }
        public Nullable<System.DateTime> dt_from { get; set; }
        public Nullable<System.DateTime> dt_to { get; set; }
    
        public virtual LokM_BasicPr LokM_BasicPr { get; set; }
    }
}
