//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOKM
    {
        public string ks200 { get; set; }
        public string ks423 { get; set; }
        public string tara { get; set; }
        public string ud { get; set; }
        public string kol_sec { get; set; }
        public string naim { get; set; }
        public string naim2 { get; set; }
    }
}
