//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LokM_Stanc_Ar
    {
        public int lokM_stanc_id { get; set; }
        public string stanc { get; set; }
        public byte Dkod { get; set; }
        public string cod_ar { get; set; }
        public Nullable<System.DateTime> dt_ar_from { get; set; }
        public Nullable<System.DateTime> dt_ar_to { get; set; }
    
        public virtual LokM_Stanc LokM_Stanc { get; set; }
    }
}
