//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LokM_Stanc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LokM_Stanc()
        {
            this.LokM_Stanc_Ar = new HashSet<LokM_Stanc_Ar>();
        }
    
        public int lokM_stanc_id { get; set; }
        public string num_lok { get; set; }
        public string ser_lok { get; set; }
        public string cod_sbs { get; set; }
        public System.DateTime dt_permit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LokM_Stanc_Ar> LokM_Stanc_Ar { get; set; }
    }
}
