//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class m104_tmp2
    {
        public string vgsnn { get; set; }
        public string vgsnv { get; set; }
        public string npfp { get; set; }
        public string rp { get; set; }
        public string p { get; set; }
        public string station { get; set; }
    }
}
