//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M109
    {
        public string kr { get; set; }
        public string pg { get; set; }
        public string vt { get; set; }
        public string ud { get; set; }
        public string utv { get; set; }
        public string mn { get; set; }
        public string mn2 { get; set; }
    }
}
