//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M122
    {
        public string n3 { get; set; }
        public string v3 { get; set; }
        public string n4 { get; set; }
        public string v4 { get; set; }
        public string n5 { get; set; }
        public string v5 { get; set; }
        public string n6 { get; set; }
        public string v6 { get; set; }
        public string n7 { get; set; }
        public string v7 { get; set; }
        public string kol_os { get; set; }
        public string tara { get; set; }
        public string ud { get; set; }
        public string dm { get; set; }
        public string grp { get; set; }
        public string usl_tip { get; set; }
        public string rod { get; set; }
        public string pr_dop { get; set; }
        public string reserv { get; set; }
    }
}
