//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M135
    {
        public string n7 { get; set; }
        public string v7 { get; set; }
        public string pr { get; set; }
        public string kod_gr { get; set; }
        public string kod_grpl { get; set; }
        public string stng { get; set; }
        public string stvg { get; set; }
        public string ktng { get; set; }
        public string ktvg { get; set; }
    }
}
