//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M142
    {
        public string n3 { get; set; }
        public string v3 { get; set; }
        public string n4 { get; set; }
        public string v4 { get; set; }
        public string pr { get; set; }
        public string ud { get; set; }
        public string dm { get; set; }
    }
}
