//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class m1673
    {
        public string kd { get; set; }
        public string ks { get; set; }
        public string mn { get; set; }
        public string mn2 { get; set; }
        public string dop { get; set; }
    }
}
