//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M170___
    {
        public string kd { get; set; }
        public string mnk { get; set; }
        public string imd { get; set; }
        public string mnk2 { get; set; }
        public string imd2 { get; set; }
    }
}
