//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class m5640
    {
        public string vnazn { get; set; }
        public string vnazv { get; set; }
        public string smnazn { get; set; }
        public string pr { get; set; }
        public string station { get; set; }
        public System.DateTime dtBegin { get; set; }
        public Nullable<System.DateTime> dtEnd { get; set; }
    }
}
