//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_NEISPRAV
    {
        public string kn { get; set; }
        public string naim { get; set; }
        public string naim2 { get; set; }
        public string kn_ukr { get; set; }
    }
}
