//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms1359_1388
    {
        public string in_vgn { get; set; }
        public System.DateTime date_op { get; set; }
        public string privat { get; set; }
        public int tip { get; set; }
        public string stanc { get; set; }
    }
}
