//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NNS_USER
    {
        public int login_id { get; set; }
        public string login_user { get; set; }
        public string password { get; set; }
        public string login_PC { get; set; }
        public string station { get; set; }
    }
}
