//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NORM
    {
        public string vid_p { get; set; }
        public string np { get; set; }
        public string ves_pr { get; set; }
        public string ud_pr { get; set; }
        public string ves_ot { get; set; }
        public string ud_ot { get; set; }
        public string station { get; set; }
    }
}
