//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPLF
    {
        public string esrn { get; set; }
        public string esrv { get; set; }
        public string kl_grpl { get; set; }
        public string kl_gr { get; set; }
        public string kl_rv { get; set; }
        public string pr_dop { get; set; }
        public string kod_grpl_n { get; set; }
        public string kod_grpl_v { get; set; }
        public string kod_gr_n { get; set; }
        public string kod_gr_v { get; set; }
        public string rodv_n { get; set; }
        public string rodv_v { get; set; }
        public string zader_tam { get; set; }
        public string pr_otv_hran { get; set; }
        public string pr_mest { get; set; }
        public string vns_nazn { get; set; }
        public string station { get; set; }
    }
}
