//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPLF2_KLIENT
    {
        public int id { get; set; }
        public string cod_kl { get; set; }
        public string nom_dog { get; set; }
        public Nullable<System.DateTime> date_dog { get; set; }
        public short long_way { get; set; }
        public decimal t_dogovornoe { get; set; }
        public string zajav { get; set; }
        public string rast_pd { get; set; }
        public int DogovId { get; set; }
    
        public virtual NPLF2 NPLF2 { get; set; }
    }
}
