//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class nsi_stanrem
    {
        public int npp { get; set; }
        public string cod_sbs { get; set; }
        public string rod_v { get; set; }
        public string min_n { get; set; }
        public string max_n { get; set; }
        public string vid_r { get; set; }
        public string st_destn { get; set; }
        public string naim_destn { get; set; }
        public string naim_destn_l { get; set; }
        public string prim { get; set; }
        public string prim_l { get; set; }
        public string pogr_st { get; set; }
        public string naim_porg { get; set; }
        public string naim_pogr_l { get; set; }
        public string stanc { get; set; }
    }
}
