//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class nsi_stan
    {
        public int npp { get; set; }
        public string cod_st { get; set; }
        public string naim { get; set; }
        public string naim_l { get; set; }
        public string adres { get; set; }
        public string kod { get; set; }
        public string ks { get; set; }
    }
}
