//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUM_POR
    {
        public string stanc { get; set; }
        public string tip_dok { get; set; }
        public string klient { get; set; }
        public string variant { get; set; }
        public string tek_nom { get; set; }
        public Nullable<System.DateTime> data_1zap { get; set; }
        public byte kol_mes { get; set; }
        public string ot { get; set; }
        public string @do { get; set; }
        public Nullable<byte> kontr { get; set; }
    }
}
