//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class park_way_VC
    {
        public string prk { get; set; }
        public string way { get; set; }
        public string prk_VC { get; set; }
        public string way_VC { get; set; }
        public string stanc { get; set; }
    }
}
