//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASS_TMP
    {
        public string np { get; set; }
        public string np_ot { get; set; }
        public string num_train { get; set; }
        public string time2 { get; set; }
        public string time3 { get; set; }
        public string station { get; set; }
    }
}
