//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pattern5676_tag5676
    {
        public int pattern5676_id { get; set; }
        public int tag5676_id { get; set; }
        public string number { get; set; }
        public int pattern5676_tag5676_id { get; set; }
    
        public virtual pattern5676 pattern5676 { get; set; }
        public virtual tag5676 tag5676 { get; set; }
    }
}
