//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class perev_ar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public perev_ar()
        {
            this.perev_lok = new HashSet<perev_lok>();
        }
    
        public string cod_per { get; set; }
        public Nullable<System.DateTime> dt_beg_ar { get; set; }
        public Nullable<System.DateTime> dt_end_ar { get; set; }
        public string prim { get; set; }
        public int id_ar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perev_lok> perev_lok { get; set; }
    }
}
