//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEREADR
    {
        public string in_vgn { get; set; }
        public string gr_por { get; set; }
        public string stanc { get; set; }
        public string cod_pol { get; set; }
        public string prim { get; set; }
        public string nom_prikaz { get; set; }
        public Nullable<System.DateTime> data_pr { get; set; }
        public string avt_del { get; set; }
        public string station { get; set; }
    }
}
