//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pw_uchastok
    {
        public string st_from_ch { get; set; }
        public string st_to_ch { get; set; }
        public string z_otv_ch { get; set; }
        public Nullable<int> sort_ch { get; set; }
        public string z_otv_nch { get; set; }
        public Nullable<int> sort_nch { get; set; }
        public int pw_id { get; set; }
        public string prim { get; set; }
        public string prim2 { get; set; }
    }
}
