//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region_stanc
    {
        public int iden { get; set; }
        public string stanc_new { get; set; }
        public string stanc_baz { get; set; }
        public int pto { get; set; }
        public int pko { get; set; }
        public int gir { get; set; }
        public int num_por_pam { get; set; }
        public int status { get; set; }
        public string naim { get; set; }
        public string napr { get; set; }
    }
}
