//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rem_Klient
    {
        public int KOD_SOB { get; set; }
        public string contract_Num { get; set; }
        public Nullable<System.DateTime> contract_DateB { get; set; }
        public Nullable<System.DateTime> contract_DateE { get; set; }
        public string Adr_tlg { get; set; }
        public Nullable<short> KodDor { get; set; }
        public int ID { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
        public string Nomer_sob { get; set; }
    }
}
