//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rem_PriceList
    {
        public int ID { get; set; }
        public int Kod { get; set; }
        public string Name { get; set; }
        public string NameLat { get; set; }
        public string SName { get; set; }
        public string SNameLat { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> KodUkr { get; set; }
    }
}
