//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RZPor
    {
        public int id { get; set; }
        public string Rod { get; set; }
        public string Nomer { get; set; }
        public string Utr { get; set; }
        public string KS { get; set; }
        public string nplf { get; set; }
        public string station { get; set; }
        public string Gruz { get; set; }
        public string st_nazn { get; set; }
    }
}
