//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sad_spis
    {
        public int id_s { get; set; }
        public string mnk { get; set; }
        public string mnk2 { get; set; }
        public string cod { get; set; }
        public string prim { get; set; }
        public string stanc { get; set; }
    }
}
