//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShablonOPKIS
    {
        public string OPKIS { get; set; }
        public string ASUS { get; set; }
        public string pole1 { get; set; }
        public string pole2 { get; set; }
        public string pole3 { get; set; }
        public string pole4 { get; set; }
        public string pole5 { get; set; }
        public string pole6 { get; set; }
        public string pole7 { get; set; }
        public string pole8 { get; set; }
        public string pole9 { get; set; }
        public string pole10 { get; set; }
        public string pole11 { get; set; }
        public string pole12 { get; set; }
        public string pole13 { get; set; }
        public string pole14 { get; set; }
        public string pole15 { get; set; }
        public string pole16 { get; set; }
        public string pole17 { get; set; }
        public string pole18 { get; set; }
        public string pole19 { get; set; }
        public string pole20 { get; set; }
    }
}
