//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class shortSort1
    {
        public Nullable<int> type { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string station { get; set; }
        public int shortSort_id { get; set; }
    }
}
