//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class shortGruz
    {
        public string code_gr { get; set; }
        public string name_gr { get; set; }
        public string name_gr2 { get; set; }
        public Nullable<int> type_gr { get; set; }
        public string station { get; set; }
        public int shortgruz_id { get; set; }
    }
}
