//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOBSTVENNIK
    {
        public int SOBSTVENNIK_ID { get; set; }
        public int KOD_SOB { get; set; }
        public string Name { get; set; }
        public string SName { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
        public short Kod_ISO { get; set; }
        public string Nomer_sob { get; set; }
        public Nullable<int> Adm_id { get; set; }
    }
}
