//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SootvPrk24
    {
        public string park_way { get; set; }
        public int way_id { get; set; }
        public Nullable<decimal> R1 { get; set; }
        public Nullable<decimal> R2 { get; set; }
        public Nullable<decimal> R3 { get; set; }
        public string stanc { get; set; }
    }
}
