//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class specvag24
    {
        public string rod { get; set; }
        public string kol_os { get; set; }
        public string usl_tip { get; set; }
        public string in_vgn { get; set; }
        public string god_p { get; set; }
        public string tara { get; set; }
        public string grp { get; set; }
        public string ud { get; set; }
    }
}
