//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPER1
    {
        public string esrnp { get; set; }
        public string np { get; set; }
        public string esrper { get; set; }
        public string pr_dop { get; set; }
        public string mnkper { get; set; }
        public string nameper { get; set; }
        public string mnkper2 { get; set; }
        public string nameper2 { get; set; }
        public string station { get; set; }
    }
}
