//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STANC
    {
        public string vid_stanc { get; set; }
        public string stanc1 { get; set; }
        public string cod_golovn { get; set; }
        public short tip_obr { get; set; }
        public short tip_otch { get; set; }
        public string e_mail { get; set; }
        public short use_in_spr { get; set; }
    }
}
