//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_cfg
    {
        public string login { get; set; }
        public string rm_tip { get; set; }
        public int log_id { get; set; }
        public int st_id { get; set; }
    
        public virtual SYS_station SYS_station { get; set; }
    }
}
