//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PK
    {
        public string LN { get; set; }
        public string LA { get; set; }
        public string PK_name { get; set; }
        public int st_id { get; set; }
        public string LN_AP { get; set; }
    }
}
