//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time_Klient
    {
        public int id { get; set; }
        public string cod_kl { get; set; }
        public string registr_kod { get; set; }
        public string nom_dog { get; set; }
        public System.DateTime date_dog { get; set; }
        public System.DateTime date_ot { get; set; }
        public System.DateTime date_do { get; set; }
        public string stanc { get; set; }
        public short pr_korr { get; set; }
        public short pr_time { get; set; }
    }
}
