//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TXT_ERR
    {
        public int err_id { get; set; }
        public string err_name { get; set; }
        public string err_name2 { get; set; }
        public int pos_from_invag { get; set; }
    }
}
