//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class uchastok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uchastok()
        {
            this.stanc_uch = new HashSet<stanc_uch>();
        }
    
        public int nom_uch { get; set; }
        public string uch_r { get; set; }
        public string uch_l { get; set; }
        public string nach_uch { get; set; }
        public string end_uch { get; set; }
        public int uch_id { get; set; }
        public int reg_id { get; set; }
    
        public virtual region region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stanc_uch> stanc_uch { get; set; }
    }
}
