//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class uslug_form
    {
        public string stanc { get; set; }
        public string kateg { get; set; }
        public int usl_id { get; set; }
    
        public virtual uslugi uslugi { get; set; }
    }
}
