//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GR_ZAP_POGR
    {
        public int H_GR_ZAP_POGR_ID { get; set; }
        public short TIP_VAG { get; set; }
        public short GRUP_GR { get; set; }
        public short PODGRUP { get; set; }
        public string NAME_GRUP { get; set; }
        public string KOD_ETSNG { get; set; }
        public string NAME_ETSNG { get; set; }
        public string COR_TIP { get; set; }
        public System.DateTime DATE_ND { get; set; }
        public System.DateTime DATE_KD { get; set; }
        public System.DateTime COR_TIME { get; set; }
    }
}
