//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.NSI_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOHR
    {
        public string num_prk { get; set; }
        public string num_log { get; set; }
        public string mne { get; set; }
        public string mne2 { get; set; }
        public Nullable<byte> kol { get; set; }
        public string itg { get; set; }
        public string station { get; set; }
    }
}
