//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AsusContext : DbContext
    {
        public AsusContext()
            : base("name=AsusContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LokM_operWork> LokM_operWork { get; set; }
        public virtual DbSet<lokomot> lokomot { get; set; }
        public virtual DbSet<oper_gr> oper_gr { get; set; }
        public virtual DbSet<park> park { get; set; }
        public virtual DbSet<rem_smen> rem_smen { get; set; }
        public virtual DbSet<rem_vag> rem_vag { get; set; }
        public virtual DbSet<rezerv> rezerv { get; set; }
        public virtual DbSet<sostav> sostav { get; set; }
        public virtual DbSet<train> train { get; set; }
        public virtual DbSet<train_rem> train_rem { get; set; }
        public virtual DbSet<vagon> vagon { get; set; }
        public virtual DbSet<way> way { get; set; }
        public virtual DbSet<char_vag> char_vag { get; set; }
        public virtual DbSet<curr_sost> curr_sost { get; set; }
        public virtual DbSet<data_sort> data_sort { get; set; }
        public virtual DbSet<lokomot_LDIS> lokomot_LDIS { get; set; }
        public virtual DbSet<lokomot_ssps> lokomot_ssps { get; set; }
        public virtual DbSet<oper_rem> oper_rem { get; set; }
        public virtual DbSet<osmotr> osmotr { get; set; }
        public virtual DbSet<rem_brig> rem_brig { get; set; }
        public virtual DbSet<rem_spec_vag> rem_spec_vag { get; set; }
        public virtual DbSet<spesl> spesl { get; set; }
        public virtual DbSet<stanz> stanz { get; set; }
        public virtual DbSet<vag_list> vag_list { get; set; }
        public virtual DbSet<vag_oper> vag_oper { get; set; }
        public virtual DbSet<vagon_204> vagon_204 { get; set; }
        public virtual DbSet<vagon_pogr_otbor> vagon_pogr_otbor { get; set; }
    }
}
