//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class asusEntities : DbContext
    {
        public asusEntities()
            : base("name=asusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LokM_operWork> LokM_operWork { get; set; }
        public virtual DbSet<park> park { get; set; }
        public virtual DbSet<vagon> vagon { get; set; }
        public virtual DbSet<way> way { get; set; }
    }
}
