//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class char_vag
    {
        public string in_vgn { get; set; }
        public string nod { get; set; }
        public string rod_v { get; set; }
        public string rod_v_pr { get; set; }
        public string usl_tip { get; set; }
        public string kol_os_v { get; set; }
        public string tip_park { get; set; }
        public string vid_v { get; set; }
        public string num_mar { get; set; }
        public string dni { get; set; }
        public Nullable<byte> prizn_v { get; set; }
        public string usl_cod_gr { get; set; }
        public string arenda { get; set; }
        public Nullable<int> intrv { get; set; }
        public string st_otpr_v { get; set; }
        public string dop_pogr_st { get; set; }
        public string dlbaz { get; set; }
        public string pr_ed { get; set; }
        public string PV_Lokm { get; set; }
        public string PV_Gruz { get; set; }
        public string PV_prS { get; set; }
        public Nullable<int> PV_KpsOtpr_id { get; set; }
        public Nullable<int> PV_AsusOtpr_id { get; set; }
    
        public virtual vagon vagon { get; set; }
    }
}
