//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LokM_operWork
    {
        public int lokM_operW_id { get; set; }
        public string stanc { get; set; }
        public int lokm_workid { get; set; }
        public string num_lok { get; set; }
        public string ser_lok { get; set; }
        public string cod_work { get; set; }
        public string cod_opL { get; set; }
        public Nullable<System.DateTime> dt_beg { get; set; }
        public Nullable<System.DateTime> dt_end { get; set; }
        public Nullable<System.DateTime> dt_ins { get; set; }
        public Nullable<int> utv { get; set; }
    }
}
