//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lokomot
    {
        public Nullable<int> train_id { get; set; }
        public string ser_lok { get; set; }
        public string num_lok { get; set; }
        public string vid_sled { get; set; }
        public Nullable<System.DateTime> time_brig { get; set; }
        public Nullable<System.DateTime> time_depo { get; set; }
        public string fam_m { get; set; }
        public string priz_lok { get; set; }
        public int lok_id { get; set; }
        public string stanc { get; set; }
        public Nullable<int> tr2_id { get; set; }
        public Nullable<int> id_per { get; set; }
        public string tab_m { get; set; }
        public string dor_prip { get; set; }
        public string kod_sost { get; set; }
        public string time_s { get; set; }
        public Nullable<System.DateTime> time_205 { get; set; }
    
        public virtual lokomot_ssps lokomot_ssps { get; set; }
        public virtual train train { get; set; }
    }
}
