//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lokomot_ssps
    {
        public int lok_id { get; set; }
        public string cod_polz { get; set; }
        public string serija { get; set; }
        public string nomer { get; set; }
    
        public virtual lokomot lokomot { get; set; }
    }
}
