//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lokomot_LDIS
    {
        public string ser_lok { get; set; }
        public string num_lok { get; set; }
        public string vid_sled { get; set; }
        public Nullable<System.DateTime> time_brig { get; set; }
        public Nullable<System.DateTime> time_depo { get; set; }
        public string fam_m { get; set; }
        public string priz_lok { get; set; }
        public string num_train { get; set; }
        public string ind_s { get; set; }
        public string stanc { get; set; }
    }
}
