//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oper_gr
    {
        public string in_vgn { get; set; }
        public string sost { get; set; }
        public string vid_r { get; set; }
        public string num_tr { get; set; }
        public Nullable<System.DateTime> date_prib { get; set; }
        public Nullable<System.DateTime> date_pereadr { get; set; }
        public string fio_uved { get; set; }
        public Nullable<System.DateTime> date_uved { get; set; }
        public Nullable<System.DateTime> date_rask { get; set; }
        public Nullable<System.DateTime> date_pod { get; set; }
        public Nullable<System.DateTime> date_osv { get; set; }
        public Nullable<System.DateTime> date_vigr { get; set; }
        public Nullable<System.DateTime> date_sdv { get; set; }
        public Nullable<System.DateTime> date_pogr { get; set; }
        public Nullable<System.DateTime> date_ubor { get; set; }
        public string cod_gr_op { get; set; }
        public string pr_op { get; set; }
        public string lokom { get; set; }
        public Nullable<bool> pr_pod { get; set; }
        public string prim { get; set; }
        public Nullable<int> prik_id { get; set; }
        public int num_241 { get; set; }
        public int num_242 { get; set; }
        public int pr_end { get; set; }
        public Nullable<int> id_zad { get; set; }
        public Nullable<System.DateTime> date_tvk { get; set; }
        public Nullable<System.DateTime> date_rast { get; set; }
        public Nullable<System.DateTime> date_tlg { get; set; }
        public Nullable<System.DateTime> date_predv_ub { get; set; }
        public Nullable<System.DateTime> date_post_kont { get; set; }
        public Nullable<System.DateTime> date_snat_kont { get; set; }
        public Nullable<System.DateTime> date_got_ubor { get; set; }
        public string prim_opl { get; set; }
        public string prim_oper { get; set; }
        public Nullable<int> pam_id { get; set; }
        public Nullable<System.DateTime> date_vigr_XML { get; set; }
        public Nullable<System.DateTime> date_pogr_XML { get; set; }
        public Nullable<int> lokMw_id { get; set; }
        public string prim_243 { get; set; }
    
        public virtual vagon vagon { get; set; }
    }
}
