//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oper_rem
    {
        public string in_vgn { get; set; }
        public string tip { get; set; }
        public string uwed { get; set; }
        public string cod { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string family { get; set; }
        public string pr_ut { get; set; }
        public Nullable<System.DateTime> beg_rem { get; set; }
        public string modern { get; set; }
        public string in_vgn_new { get; set; }
        public string dop_inf_ns { get; set; }
        public int oper_rem_id { get; set; }
    }
}
