//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osmotr
    {
        public int tr_rem_id { get; set; }
        public string otv { get; set; }
        public string family { get; set; }
        public string gol_vag { get; set; }
        public Nullable<short> ord_num { get; set; }
    
        public virtual train_rem train_rem { get; set; }
    }
}
