//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class park
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public park()
        {
            this.way = new HashSet<way>();
        }
    
        public string num_prk { get; set; }
        public string name_park_l { get; set; }
        public string name_park_r { get; set; }
        public Nullable<byte> tip_prk { get; set; }
        public string stanc { get; set; }
        public int prk_id { get; set; }
        public Nullable<int> sort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<way> way { get; set; }
    }
}
