//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rem_spec_vag
    {
        public string in_vgn { get; set; }
        public string reason { get; set; }
        public string stanc { get; set; }
        public System.DateTime date_c { get; set; }
    }
}
