//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rem_brig
    {
        public string fio { get; set; }
        public string tip { get; set; }
        public Nullable<int> rem_smen_id { get; set; }
        public Nullable<int> num { get; set; }
        public string park { get; set; }
        public string stanc { get; set; }
    }
}
