//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rem_vag
    {
        public string in_vgn { get; set; }
        public string vid_r { get; set; }
        public string ind_s { get; set; }
        public string num_train { get; set; }
        public Nullable<System.DateTime> data_prib { get; set; }
        public string vid_v { get; set; }
        public string rod_v { get; set; }
        public Nullable<System.DateTime> data_postr { get; set; }
        public string vid_rp { get; set; }
        public Nullable<System.DateTime> data_rp { get; set; }
        public string place_rp { get; set; }
        public string cod_sbs { get; set; }
        public string grup { get; set; }
        public string sost { get; set; }
        public string place_remf { get; set; }
        public Nullable<short> vc1353 { get; set; }
        public Nullable<short> vc1354 { get; set; }
        public string belong { get; set; }
        public Nullable<int> tr_rem_id { get; set; }
        public Nullable<byte> tip_br { get; set; }
        public string disloc { get; set; }
        public string place_wh { get; set; }
        public string cod_rem { get; set; }
        public string stanc { get; set; }
        public Nullable<byte> vid_br { get; set; }
        public string st_destn { get; set; }
        public Nullable<short> vc1352 { get; set; }
    
        public virtual train_rem train_rem { get; set; }
    }
}
