//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezerv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rezerv()
        {
            this.vagon = new HashSet<vagon>();
        }
    
        public int rezerv_id { get; set; }
        public string kod_rez { get; set; }
        public Nullable<System.DateTime> data_ot { get; set; }
        public string index_rez { get; set; }
        public string num_pr_rez { get; set; }
        public Nullable<System.DateTime> date_pr_rez { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vagon> vagon { get; set; }
    }
}
