//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sostav
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sostav()
        {
            this.curr_sost = new HashSet<curr_sost>();
            this.train = new HashSet<train>();
            this.vagon = new HashSet<vagon>();
        }
    
        public int sostav_id { get; set; }
        public Nullable<int> way_id { get; set; }
        public string ind_s { get; set; }
        public string tip_s { get; set; }
        public string por_gr { get; set; }
        public string usl_dl_s { get; set; }
        public string ves_s { get; set; }
        public string prikr_s { get; set; }
        public string negab_s { get; set; }
        public string ziwn_s { get; set; }
        public string mar_s { get; set; }
        public string ohr_s { get; set; }
        public string tara_s { get; set; }
        public string netto_s { get; set; }
        public string otv_pt { get; set; }
        public string otv_ot { get; set; }
        public string num_vag_h { get; set; }
        public string num_vag_t { get; set; }
        public string pv_p { get; set; }
        public string pv_o { get; set; }
        public int pr_razl { get; set; }
        public string zvk_tr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curr_sost> curr_sost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<train> train { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vagon> vagon { get; set; }
    }
}
