//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stanz
    {
        public string num_stan { get; set; }
        public string name_stan_r { get; set; }
        public string name_stan_l { get; set; }
        public string nod { get; set; }
        public string num_stan_osn { get; set; }
        public string vid { get; set; }
        public string napr1 { get; set; }
        public string napr2 { get; set; }
        public string num_stan6 { get; set; }
        public string num_stan_KPS { get; set; }
        public string num_stan_osn_KPS { get; set; }
    }
}
