//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class train
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public train()
        {
            this.lokomot = new HashSet<lokomot>();
        }
    
        public int train_id { get; set; }
        public Nullable<int> sostav_id { get; set; }
        public string cod_per { get; set; }
        public string num_train { get; set; }
        public string priz_spis { get; set; }
        public Nullable<System.DateTime> data_tr { get; set; }
        public byte face { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lokomot> lokomot { get; set; }
        public virtual sostav sostav { get; set; }
    }
}
