//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class train_rem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public train_rem()
        {
            this.rem_vag = new HashSet<rem_vag>();
        }
    
        public int tr_rem_id { get; set; }
        public string vid { get; set; }
        public string ind_s { get; set; }
        public string num_train { get; set; }
        public Nullable<System.DateTime> data_op { get; set; }
        public Nullable<int> pr_to { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rem_vag> rem_vag { get; set; }
        public virtual osmotr osmotr { get; set; }
    }
}
