//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vag_list
    {
        public string in_vgn { get; set; }
        public string primech { get; set; }
        public string cod_gr { get; set; }
        public string cod_grp { get; set; }
        public int ves { get; set; }
        public int vag_id { get; set; }
        public string st_pereh { get; set; }
        public string cod_str { get; set; }
        public string sposob_opr_m { get; set; }
        public string kont { get; set; }
        public string max_negab { get; set; }
        public string num_marsh { get; set; }
        public short ves_tara { get; set; }
        public string marsh { get; set; }
        public Nullable<int> num_por241 { get; set; }
        public Nullable<int> num_por242 { get; set; }
        public string punkt_vigr { get; set; }
        public string vid_r_sdv { get; set; }
        public string sapod_raskr { get; set; }
        public string otmetki { get; set; }
    }
}
