//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vag_oper
    {
        public string in_vgn { get; set; }
        public Nullable<int> way_id { get; set; }
        public string ind_s { get; set; }
        public Nullable<System.DateTime> data_op { get; set; }
        public int op_id { get; set; }
    }
}
