//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vagon_pogr_otbor
    {
        public string in_vgn { get; set; }
        public System.DateTime date_check { get; set; }
        public string godn { get; set; }
        public string route { get; set; }
        public string rw_dest { get; set; }
        public string code_godn_gr { get; set; }
        public string fio { get; set; }
        public string note { get; set; }
        public string station { get; set; }
        public Nullable<int> id_z { get; set; }
        public Nullable<short> type { get; set; }
        public int vagon_pogr_otbor_id { get; set; }
    }
}
