//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vagon
    {
        public string in_vgn { get; set; }
        public Nullable<int> way_id { get; set; }
        public Nullable<short> ord_num { get; set; }
        public Nullable<int> sostav_id { get; set; }
        public Nullable<int> rezerv_id { get; set; }
        public string priz_k { get; set; }
        public string cod_sbs { get; set; }
        public string rolik { get; set; }
        public string ves_gruz { get; set; }
        public string st_destn { get; set; }
        public string cod_gruz { get; set; }
        public string cod_grpl { get; set; }
        public string mach { get; set; }
        public string cod_prk { get; set; }
        public string negab_vg { get; set; }
        public string plomb { get; set; }
        public string knt_stn { get; set; }
        public string knt_ktn { get; set; }
        public string srok { get; set; }
        public string pogr_st { get; set; }
        public string tara { get; set; }
        public string prim { get; set; }
        public string privat { get; set; }
    
        public virtual way way { get; set; }
    }
}
