//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGAT.LocoDispatcher.AsusDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vagon_204
    {
        public string in_vgn { get; set; }
        public string god_p { get; set; }
        public string st_pogr { get; set; }
        public string st_arenda { get; set; }
        public string st_prp { get; set; }
        public string str_sv { get; set; }
        public string prim { get; set; }
        public string remont { get; set; }
        public string ost_prob { get; set; }
        public string tara { get; set; }
        public string grpd { get; set; }
        public string etsng { get; set; }
        public string kd { get; set; }
        public string rsv { get; set; }
        public string sv { get; set; }
        public string usl_dl { get; set; }
        public string priv_204 { get; set; }
        public string nrp { get; set; }
        public string vrv { get; set; }
        public string ksA { get; set; }
        public string nsA { get; set; }
        public string npA { get; set; }
        public string dtA { get; set; }
    }
}
