// <auto-generated />
namespace AGAT.LocoDispatcher.AuthDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class removePasswordConstraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removePasswordConstraint));
        
        string IMigrationMetadata.Id
        {
            get { return "202010141336227_removePasswordConstraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
