// <auto-generated />
namespace AGAT.LocoDispatcher.AuthDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class addOneToManyrelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addOneToManyrelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202010131241556_addOneToManyrelationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
